# NAME: Atibhav Mittal
# EMAIL: atibhav.mittal6@gmail.com
# ID: 804598987

CC=gcc
CFLAGS=-Wall -Wextra
TARGET=lab1a

$(TARGET): $(TARGET).c
	$(CC) $(TARGET).c $(CFLAGS) -o $(TARGET)

clean: 
	rm -f lab1a lab1a-804598987.tar.gz

dist:
	tar -cvzf lab1a-804598987.tar.gz README Makefile lab1a.c